include:
  - component: $CI_SERVER_HOST/devops/ci-components/kaniko/kaniko@1
    inputs:
      auto: true
  - component: $CI_SERVER_HOST/devops/ci-components/deploy/dockerhost@1
    inputs:
      DEPLOYPATH: "/home/docker/$CI_PROJECT_NAME"
      DEPLOYIMG: $BUILDEDIMG
      DEPLOYUSER: "root"
      DEPLOYSERVER: "172.29.2.35"
      DEPLOYSSH: $SSH_PRIVATE_KEY
      DEPLOTYPE: "0"

kaniko:
  needs:
    - build

deploytodockerhost:
  needs:
    - kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY: "YES"
build:
  interruptible: true
  image: registry-gitlab.tdbm.mn/devops/container-images/node:18
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .next/static/
      - .next/standalone/
  variables:
    CI: false
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
